### ISSUE TITLE
Add fields for secondStage

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting-extensions/ocds_secondStageDescription_extension#2]
TED forms have successiveReduction and noNegotiationNecessary at procedure (tender) level. eForms have these at lot level.

**Comment by ColinMaudry** [comment]
We could have the same approach as for the procedure extension, and have a `SecondStage` object that can be attached either to a `Tender` or to `Lot`.

**Comment by jpmckinney** [comment]
Indeed. Do you want to make the change? I had already updated the readme and extension.json but ran out of time to update the schema.

**Comment by ColinMaudry** [comment]
So far, successiveReduction was implemented in `[ocds_procurementMethodModalities_extension](https://github.com/open-contracting-extensions/ocds_procurementMethodModalities_extension)`, along with `procurementMethodName` for instance.

I consequently move it to `ocds_secondStage`.

**Comment by ColinMaudry** [comment]
Regarding noNegotiationNecessary, I reported my concerns about the label: eForms/eForms/issues/323

**Comment by jpmckinney** [comment]
Closed by #3
